### ISSUE TITLE
Sporadic exception when exiting with sys.exit

### ISSUE THREAD

**Issue by Noctevent** [paramiko/paramiko#1078]
Around 20% of the time, my script which uses paramiko for a simple ssh command:

```
ssh = SSHClient()
ssh.load_system_host_keys()
try:
    ssh.connect(machine, username=user, password=password)
    stdin, stdout, stderr = ssh.exec_command(commande)

    return_code = stdout.channel.recv_exit_status()

    out = stdout.read().decode('utf-8')
    err = stderr.read().decode('utf-8')

    if out.strip():
        print(out.strip())
    if err.strip():
        print(err.strip())

    # stderr.close()
    # stdout.close()
    # stdin.close()

    # print("CR=" + str(code_retour))
    print("CR=0")
    rc = 0

except SSHException as e:
    print(e)
    rc = -2
finally:
    ssh.close()

sys.exit(cr)
```
Spews out those exceptions:
```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 62, in __del__
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 80, in close
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 89, in flush
TypeError: 'NoneType' object is not callable
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 62, in __del__
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 80, in close
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 89, in flush
TypeError: 'NoneType' object is not callable
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 62, in __del__
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 80, in close
  File "/home/user/.miniconda2/envs/py3/lib/python3.5/site-packages/paramiko/file.py", line 89, in flush
TypeError: 'NoneType' object is not callable
```
This does look like #17, but does not occur in the same context. If I remove `sys.exit` from my script, the error does not seem to occur anymore (or maybe at a greatly reduced rate, which caused me not to observe it after 50 runs or so).

**Comment by Noctevent** [comment]
**Update**
The error does not occur when the program is not exited with `sys.exit`. So I tried wrapping my whole script in a function, calling that function and then calling `sys.exit` so that the latter does not run in the same scope as the paramiko SSHClient, and magic, the error seems to have vanished.

**Comment by jhmenke** [comment]
This is still an issue in the current version.

**Comment by STejas91** [comment]
still seeing same issue as above.
`Exception ignored in: <function BufferedFile.__del__ at 0x0000029589DEF3A8>
Traceback (most recent call last):
  File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\file.py", line 66, in __del__
  File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 1392, in close
  File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 991, in shutdown_write
  File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 963, in shutdown
  File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 1246, in _send_eof
  File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\message.py", line 232, in add_int
TypeError: 'NoneType' object is not callable`

**Comment by STejas91** [comment]
still seeing same issue as above.

> Exception ignored in: <function BufferedFile.__del__ at 0x0000029589DEF3A8> Traceback (most recent call last): File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\file.py", line 66, in __del__ File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 1392, in close File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 991, in shutdown_write File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 963, in shutdown File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\channel.py", line 1246, in _send_eof File "C:\Users\ts\PycharmProjects\tzx_learning\venv\lib\site-packages\paramiko\message.py", line 232, in add_int TypeError: 'NoneType' object is not callable

**Comment by ben-dyer** [comment]
New to paramiko, getting the same error and traceback as @STejas91, but I'm not using `sys`. `_send_eof File` made me wonder if its related to https://github.com/paramiko/paramiko/pull/1585.

**Comment by Dynan7** [comment]
Same problem
paramiko==2.7.1
Python 3.7.5

```
import paramiko

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.1.5', username='pi', password='789')
stdin, stdout, stderr = ssh.exec_command("sudo ifconfig")

stdout_str = stdout.read().decode('utf-8')
print(stdout_str)


ssh.close()
```

**Comment by metaMMA** [comment]
I also am seeing this issue [here](https://github.com/Flexget/Flexget/blob/ad3a8cd63c94c99799594f99342e15276741d414/flexget/plugins/operate/free_space.py#L14-L28)

**Comment by STejas91** [comment]
Guys, i found that the IP i was using had network connection issue and once i fixed that my code started working just fine. I would suggest you all to cross check the IP's and access you guys are using to connect.

**Comment by BertCatsburg** [comment]
Problem remains. No problem with the network connection (@STejas91) since I got the output. 
Program is:
```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=PRODUCTION_SERVER, port=22, username=PRODUCTION_USER)
stdin, stdout, stderr = client.exec_command('echo "Hello World"')

for line in stdout:
    print(line.strip('\n'))

client.close()
```

Output: 
```
Hello World
Exception ignored in: <function BufferedFile.__del__ at 0x106dff378>
Traceback (most recent call last):
  File "/Users/bert/pytest/venv/lib/python3.7/site-packages/paramiko/file.py", line 66, in __del__
  File "/Users/bert/pytest/venv/lib/python3.7/site-packages/paramiko/channel.py", line 1392, in close
  File "/Users/bert/pytest/venv/lib/python3.7/site-packages/paramiko/channel.py", line 991, in shutdown_write
  File "/Users/bert/pytest/venv/lib/python3.7/site-packages/paramiko/channel.py", line 963, in shutdown
  File "/Users/bert/pytest/venv/lib/python3.7/site-packages/paramiko/channel.py", line 1246, in _send_eof
  File "/Users/bert/pytest/venv/lib/python3.7/site-packages/paramiko/message.py", line 232, in add_int
TypeError: 'NoneType' object is not callable
```

**Comment by STejas91** [comment]
@BertCatsburg Are you able to connect to the host via ssh on terminal ?
and hope you are passing password parameter for "client.connect".

**Comment by BertCatsburg** [comment]
@STejas91  Yes, I can connect via terminal. Password not necessary since I have the Public/Private key pair set up between client and host. Logging in via terminal is therefore by doing:
```
$ ssh user@host
```

**Comment by STejas91** [comment]
@BertCatsburg If you are using passwordless authentication try below, this should work.
`privatekeyfile = os.path.expanduser('~/.ssh/id_rsa')
mykey = paramiko.RSAKey.from_private_key_file(privatekeyfile)
ssh.connect(IP, username = user, pkey = mykey)`

**Comment by RafaARV** [comment]
@BertCatsburg I was getting exactly the same error. For me it was a garbage collector error so, in order to work around this I did my own deletion:

```
if client is not None:
    client.close()
    del client, stdin, stdout, stderr
```

Hope this helps.

**Comment by rgezikov** [comment]
My experience shows that deleting just stdin is enough. But clearly it has to be fixed in the library.

**Comment by pranavmarla** [comment]
@RafaARV @rgezikov Anecdotally, looks like just setting stdin to None works as well.

**Comment by vvelan** [comment]
For what it's worth, I also have this same issue (Paramiko 2.7.1 and Python 3.6.9), and it seems that deleting stdin suffices to suppress the error message. Tough to say for certain because the TypeError is irregular and does not appear every time I execute the Python script.

```
import paramiko, getpass

client = paramiko.SSHClient()
client.load_system_host_keys()
password = getpass.getpass("Password: ")
client.connect('192.168.0.10', username='USER', password=password)

# test.exe is a simple C++ program on a Windows machine. It reads floats,
# adds them to a variable, and prints the current value of that variable.
stdin, stdout, stderr = client.exec_command('.\\Desktop\\test.exe')
stdin.write('5\n')
stdin.write('10\n')
stdin.write('-3.5\n')
stdin.write('-4.5\n')
stdin.write('-1\n')
for line in stdout.readlines():
    print(line[:-1])
print(stderr.readlines())
print(stdout.channel.recv_exit_status())

client.close()
# del stdin
```

**Comment by konflic** [comment]
Still occurs paramiko 2.7.2
del stdin helps

**Comment by eMTyMe** [comment]
Still occurs paramiko==3.4.0
Again `del stdin` removes it
To be honest, by now this should be fixed, it's been 7 years

**Comment by danielfaust** [comment]
I also have this without calling `sys.exit`. When I use `os.system('python3 script_that_uses_paramiko.py')` in a Python script, I randomly get those messages when `script_that_uses_paramiko.py` exits. Though my error is a bit different, but feels related:

```
Exception ignored in: <function BufferedFile.__del__ at 0x7f3328749c60>
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/mambaforge-23.11.0-0/envs/p312-letsencrypt-2024-06-17/lib/python3.12/site-packages/paramiko/file.py", line 67, in __del__
  File "/home/user/.pyenv/versions/mambaforge-23.11.0-0/envs/p312-letsencrypt-2024-06-17/lib/python3.12/site-packages/paramiko/channel.py", line 1390, in close
  File "/home/user/.pyenv/versions/mambaforge-23.11.0-0/envs/p312-letsencrypt-2024-06-17/lib/python3.12/site-packages/paramiko/channel.py", line 989, in shutdown_write
  File "/home/user/.pyenv/versions/mambaforge-23.11.0-0/envs/p312-letsencrypt-2024-06-17/lib/python3.12/site-packages/paramiko/channel.py", line 965, in shutdown
  File "/home/user/.pyenv/versions/mambaforge-23.11.0-0/envs/p312-letsencrypt-2024-06-17/lib/python3.12/site-packages/paramiko/transport.py", line 1936, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
```
